### ISSUE TITLE
Using :after

### ISSUE THREAD

**Issue by desislavsd** [tailwindlabs/tailwindcss-aspect-ratio#4]
Hey @adamwathan , thanks for your great work!

I just wanted to ask if you have considered using `:after` element for the padding and what key points made you decide against it?

I usually go with something like this:

```css
[class*="aspect-ratio"] {
  position: relative;
  display: block;
}
[class*="aspect-ratio"]:after{
  content: '';
  display: block;
  padding-bottom: var(--aspect-ratio, 100%);
}
[class*="aspect-ratio"] > * {
  position: absolute;
}
.aspect-ratio-square {
  --aspect-ratio: 100%;
}
```
The pros of course are that we don't need an extra parent element.

I assume one con is that u cannot target the `:after` element with other utilities, also this way the selector is a bit stronger, but, while this is subjective, I cannot think of a common enough scenario that this would be a problem. Anyway you made it with purpose and I am just curious 😊
